### ISSUE TITLE
String Value in the response is coming as null

### ISSUE THREAD

**Issue by aashish-chaubey** [aashish-chaubey/graphql-example#1]
## Issue:
When we query for the API through the REST client, the response is a little peculiar. In that, all the String keys hold a value of null even though there is String data in the database.

Screenshots are attached below:

![image](https://user-images.githubusercontent.com/12701463/77423769-f00cb080-6df5-11ea-8134-22f66e686972.png)

## Reproduce the error:
- Set up a MySQL database as mentioned in the README.md of the project. 
- Configure the database
- Run the project as guided by the README file.
- Query for the endpoint `/api/v1/employee` with the query in the body as
```
{
	getAllEmployees {
		id
		first_name
		last_name
		salary
	}
}
```
- Check the output.

This is my query response:
```
{
    "errors": [],
    "data": {
        "getAllEmployees": [
            {
                "id": 1,
                "first_name": null,
                "last_name": null,
                "salary": 5500
            },
            {
                "id": 2,
                "first_name": null,
                "last_name": null,
                "salary": 7200
            },
            {
                "id": 3,
                "first_name": null,
                "last_name": null,
                "salary": 6000
            },
            {
                "id": 4,
                "first_name": null,
                "last_name": null,
                "salary": 6800
            },
            {
                "id": 5,
                "first_name": null,
                "last_name": null,
                "salary": 4750
            },
            {
                "id": 6,
                "first_name": null,
                "last_name": null,
                "salary": 5100
            },
            {
                "id": 7,
                "first_name": null,
                "last_name": null,
                "salary": 8500
            },
            {
                "id": 8,
                "first_name": null,
                "last_name": null,
                "salary": 8000
            }
        ]
    },
    "extensions": null
}
```

## Environment:
I am running on MacOS Catalina Version `10.15.3`
Java Version: ` 12.0.1`
graphql-spring-boot-starter version: `3.6.0`

**Comment by callmemansoor** [comment]
[Pull Request](https://github.com/aashish-chaubey/graphql-example/pull/2) Has Been Raised For This Issue.

Screenshot of successfull api response :

![Screenshot (275)](https://user-images.githubusercontent.com/15903110/77459846-501b4b00-6e26-11ea-8b58-6d61f39cd260.png)

As shown in above imaage request query should be : 

{
	getAllEmployees {
		id
		firstName
		lastName
		jobTitle
		salary
	}
}

instead of : 
 {
	getAllEmployees {
		id
		first_name
		last_name
                job_title
		salary
	}
}

Query Parameters name should be similar to variable names defined in the pojo .

**Comment by aashish-chaubey** [comment]
@mansoor7866  thanks for the PR, this fixes the issue!
